dependencies:
  # - organization/repo>@<version>, para descargar paquetes de solidity desde GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.4.2

compiler:
  solc:
    remappings:
    # de esta forma cualquier parte del código en el que diga @chainlink, entendera que es smartcontractkit/chainlink-brownie-contracts@1.1.1
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'

dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development: 
    verify: False
  ganache-local:
    verify: False
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify: True    
wallets:
# environment variable set up for private key
  from_key: ${PRIVATE_KEY}
  account_name: "metamask_1"


